### ISSUE TITLE
issue with sh

### ISSUE THREAD

**Issue by sysadmin-info** [gamehelp16/now-clocking#4]
If anyone have issue with sh, and the cover is not displaying, open these files: 
spotifyart
cmusart
and change #!/bin/sh to #!/bin/bash
additionally in spotifyart change url=${test/https:\/\/open.spotify.com/http:\/\/i.scdn.co} to 
url=${test/https:\/\/open.spotify.com/https:\/\/i.scdn.co}

(added https instead of http)

Then open
np
npart
and change exec sh to exec bash

**Comment by sysadmin-info** [comment]
Issue solved.

**Comment by gamehelp16** [comment]
Hello! Since this conky widget was originally intended for my own personal use only, when making it I didn't really give too much thought about "future proofing" it nor trying to make the code clean. All I cared about was just to make the widget work for me, so it isn't surprising if some issues might arise for some people thus some fixes need to be done. So, I just want to say thank you for submitting this issue and #3 as well ;)
